name: 'Setup Common Tools'
description: 'JDK, AWS Auth, Terraform Setup'
inputs:
  aws-access-key:
    required: true
  aws-secret-key:
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ap-northeast-2